services:
  - type: web
    name: metabase
    env: docker
    repo: https://github.com/render-examples/metabase.git # optional
    plan: standard # ensure that metabase has at least 2GB of RAM (defaults to starter)
    autoDeploy: false
    envVars:
      - key: postgres://default:apeMw2XNcFv1@ep-red-frog-74355594-pooler.us-east-1.postgres.vercel-storage.com:5432/verceldb?pgbouncer=true&connect_timeout=15
        fromDatabase:
          name: verceldb
