services:
  - type: web
    name: metabase
    env: docker
    repo: https://github.com/render-examples/metabase.git # optional
    plan: standard # ensure that metabase has at least 2GB of RAM (defaults to starter)
    autoDeploy: false
    envVars:
      - key: postgres://metabase_hot8_user:xkXI9qAyT50PHgmYh24NbXIddXDJd4jW@dpg-cldredglkhpc73fatdb0-a/metabase_hot8
        fromDatabase:
          name: elephant
          property: connectionString
databases:
  - name: elephant
    databaseName: metabasedb
    ipAllowList: [] # only allow internal connections
